#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: $0 <file>"
	exit
else
	img="$1"
fi

if [ ! -f "$img" ]; then
	echo "$img: Not a file"
	exit
fi

label=`basename "$img" | tr 'a-z-' 'A-Z_' | sed 's/\.[A-Z]*$//'`
identify -format "\$WIDTH_$label: %wpx\n" "$img"
identify -format "\$HEIGHT_$label: %hpx\n" "$img"
